name: etrip
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  logger: 0.9.4
  url_launcher: 5.7.10
  firebase_messaging: 7.0.3
  geolocator: 6.1.7
  get_storage: 1.3.2
  search_map_place: ^0.3.0
  location: 3.0.2
  geocoder: 0.2.1
  jwt_decoder: 1.0.3
  flutter_secure_storage: 3.3.5
  http: 0.12.2
  form_field_validator: 1.0.1
  firebase_auth: 0.18.3+1
  firebase_core: 0.5.2+1
  google_fonts: 1.1.1
  pin_entry_text_field: 0.1.4
  multiselect_formfield: 0.1.4
  carousel_slider: ^2.3.1
  image_picker: ^0.6.7+14
  get: 3.17.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: BoringSans
      fonts:
        - asset: assets/fonts/Boring-Sans-A-Bold.ttf