# Generated by Django 3.0.11 on 2020-11-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20201118_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
