# Generated by Django 3.0.11 on 2020-11-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_auto_20201115_2225'),
        ('trips', '0003_trip_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle'),
        ),
    ]
