# Generated by Django 3.0.11 on 2020-11-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_status',
            field=models.IntegerField(blank=True, choices=[(0, 'OnBid'), (1, 'BidSelected'), (2, 'Cancelled'), (3, 'EnRoute'), (4, 'Completed')], default=0),
        ),
    ]
