# Generated by Django 3.0.11 on 2020-11-22 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201119_0213'),
        ('trips', '0005_trip_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bid_status', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Applied'), (2, 'Approved'), (3, 'Cancelled')], default=0)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Driver')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.Trip')),
            ],
        ),
    ]
