# Generated by Django 3.0.11 on 2020-11-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_bid_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_status',
            new_name='status',
        ),
    ]
