# Generated by Django 3.0.11 on 2020-11-22 17:17

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_auto_20201122_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='from_place_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(75.7804, 11.2588), srid=4326),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_place_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(76.2673, 9.9312), srid=4326),
        ),
    ]
