# Generated by Django 3.0.11 on 2020-11-23 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0010_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='device_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
