# Generated by Django 3.0.11 on 2020-11-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_auto_20201123_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='users',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'TripCreated'), (1, 'BidCreated'), (2, 'BidApproved')], default=0),
        ),
    ]
