# Generated by Django 3.0.11 on 2020-11-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_auto_20201123_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='selected_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_selected', to='trips.Bid'),
        ),
    ]
