# Generated by Django 3.0.11 on 2020-11-22 18:26

from django.db import migrations, models
import e_trip.management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_banner', models.FileField(default='file.jpeg', help_text='Ad Slider Image', upload_to=e_trip.management.models.admin_directory_path)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(default='Default Profile', max_length=50)),
                ('max_bid_notification_limit', models.IntegerField(default=10)),
                ('max_bid_search_range', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
