# Generated by Django 3.0.11 on 2020-11-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='name',
            field=models.CharField(default='Default Ads', max_length=50),
        ),
    ]
