# Generated by Django 3.0.11 on 2020-11-14 12:47

from django.db import migrations, models
import e_trip.vehicles.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='file',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='icon',
            field=models.FileField(default='file.pdf', help_text='MaterialFiles', upload_to=e_trip.vehicles.models.material_directory_path),
        ),
    ]
