# Generated by Django 3.0.11 on 2020-11-14 12:49

from django.db import migrations, models
import e_trip.vehicles.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20201114_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='icon',
            field=models.FileField(default='file.pdf', help_text='Display Icon', upload_to=e_trip.vehicles.models.material_directory_path),
        ),
    ]
