# Generated by Django 3.0.11 on 2020-11-15 15:54

from django.db import migrations, models
import django.db.models.deletion
import e_trip.vehicles.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201115_0131'),
        ('vehicles', '0004_auto_20201114_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='icon',
            field=models.FileField(default='icon.png', help_text='Display Icon', upload_to=e_trip.vehicles.models.material_directory_path),
        ),
        migrations.CreateModel(
            name='DriverVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(default='file.jpeg', help_text='Vehicle Image', upload_to=e_trip.vehicles.models.driver_directory_path)),
                ('vehicle_no', models.CharField(max_length=30)),
                ('is_permited', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle')),
            ],
        ),
    ]
