# Generated by Django 3.0.11 on 2020-11-15 16:53

import datetime
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20201115_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivervehicle',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
        migrations.AddField(
            model_name='drivervehicle',
            name='last_location_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 16, 53, 20, 259681, tzinfo=utc)),
        ),
    ]
