# Generated by Django 3.0.11 on 2020-11-15 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_auto_20201115_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivervehicle',
            name='last_location_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
