# Generated by Django 3.0.11 on 2020-11-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201113_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='status',
            new_name='driver_status',
        ),
        migrations.AddField(
            model_name='driver',
            name='is_document_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
