# Generated by Django 3.0.11 on 2020-11-14 20:01

from django.db import migrations, models
import e_trip.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201115_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license',
            field=models.FileField(default='license.jpeg', upload_to=e_trip.users.models.driver_directory_path),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.FileField(default='photo.jpeg', upload_to=e_trip.users.models.driver_directory_path),
        ),
    ]
