# Generated by Django 3.0.11 on 2020-11-15 18:55

from django.db import migrations, models
import e_trip.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201115_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='license',
            new_name='license_back',
        ),
        migrations.AddField(
            model_name='driver',
            name='license_front',
            field=models.FileField(default='license.jpeg', upload_to=e_trip.users.models.driver_directory_path),
        ),
    ]
