# Generated by Django 3.0.11 on 2020-11-22 07:52

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201119_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='current_place_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(75.7804, 11.2588), srid=4326),
        ),
    ]
